### ISSUE TITLE
Playing videos

### ISSUE THREAD

**Issue by MazenSenih** [hajduakos/PanoDotNet#2]
Hi, do think there is a way to play a video rendering directly on the sphere, without having to extract frames out of it?!

**Comment by hajduakos** [comment]
My knowledge about WPF is not so deep, but as far as I know it is possible. Instead of using an `ImageBrush` as the texture of the sphere, you could use a `MediaElement`. You should try searching for some example where a `MediaElement` is put on a 3D object.

**Comment by MazenSenih** [comment]
Thanks for your response, I will do a research about that  :+1: , Keep up the great work!.

Regards
